### ISSUE TITLE
Sponsored posts not getting removed

### ISSUE THREAD

**Issue by plan291037** [mgziminsky/FacebookTrackingRemoval#34]
now, It doesn't work 
![image](https://user-images.githubusercontent.com/22098092/79042422-f9817f80-7c21-11ea-9556-1adfaf96af48.png)

**Comment by mgziminsky** [comment]
Thanks for reporting. I'm aware of the issue and working on it. Facebook recently made a change that made detection much more difficult.

Only sponsored post detection is broken, everything else still works fine.

**Comment by mgziminsky** [comment]
Would you try adding this to the custom CSS selector box under advanced options and seeing if it works for you. I have a feeling that if it does, it won't for long, but if we're lucky it will keep working for a while. If it works for you and doesn't break anything, I'll add it to the extension.

`span.d_1hcf_5tgqc`

<img width="344" alt="screenshot" src="https://user-images.githubusercontent.com/1260554/79056473-83dbda80-7c46-11ea-94ef-2da0b706afc5.png">

**Comment by plan291037** [comment]
Thank you very much, Still not working. It has a red frame added in.
![image](https://user-images.githubusercontent.com/22098092/79127894-d515d680-7dcc-11ea-8e00-97b7f288addf.png)


> คุณจะลองเพิ่มสิ่งนี้ลงในกล่องตัวเลือก CSS ที่กำหนดเองภายใต้ตัวเลือกขั้นสูงและดูว่าเหมาะกับคุณหรือไม่ ฉันมีความรู้สึกว่าถ้าเป็นเช่นนั้นมันจะไม่นาน แต่ถ้าเราโชคดีมันจะทำงานต่อไปสักพัก ถ้ามันเหมาะกับคุณและไม่ทำลายอะไรเลยฉันจะเพิ่มมันเข้าไปในส่วนขยาย
> 
> `span.d_1hcf_5tgqc`
> 
> <img alt="ภาพหน้าจอ" width="344" src="https://user-images.githubusercontent.com/1260554/79056473-83dbda80-7c46-11ea-94ef-2da0b706afc5.png">

**Comment by mgziminsky** [comment]
Are sponsor posts still showing for you? They started working on their own again for me, so I haven't been able to investigate any more

**Comment by Pezor** [comment]
I'm still seeing sponsored posts, tried the above solution, but with no success.

![01](https://user-images.githubusercontent.com/6975523/80249703-9dcbe300-8672-11ea-8a5c-4a0283f9f355.png)
![02](https://user-images.githubusercontent.com/6975523/80249717-9f95a680-8672-11ea-8faf-33f57a94d6f3.png)

**Comment by mgziminsky** [comment]
@Pezor 

Thanks for providing that devtools screenshot, I should be able to update the rules to handle your case at least. I just pushed an update to the pending ruleset soon, so make sure it is enabled under the advanced options and hit "Refresh Rules". If you confirm it works, and i don't notice any other issues, i'll release it to the main ruleset

**Comment by Pezor** [comment]
@mgziminsky Unfortunately it seems like I'm still getting sponsored posts, despite enabling the pending/unconfirmed rules. If I can post anything else than these devtools screenshots to help you let me know. Below are 3 another examples.

![01](https://user-images.githubusercontent.com/6975523/80309983-91619a80-87d8-11ea-9484-3242cd89f362.png)
![02](https://user-images.githubusercontent.com/6975523/80309986-94f52180-87d8-11ea-88d3-aa3bead90d10.png)
![03](https://user-images.githubusercontent.com/6975523/80309988-958db800-87d8-11ea-8704-3ed0a3da329c.png)

**Comment by plan291037** [comment]
facebook have new style. I don't know if it's related or not.
![image](https://user-images.githubusercontent.com/22098092/80312118-b45a7180-880d-11ea-9fb2-2a15f74c27dd.png)

**Comment by mgziminsky** [comment]
@plan291037 @Pezor

I finally received the new design so that I could look into this. Everything should now be working in v1.8.1. Can you check that it works for you and close this issue if so. The new version is live on Firefox, it will be a little while still until it goes live on Chrome though.

**Comment by plan291037** [comment]
> @plan291037 @Pezor
> 
> I finally received the new design so that I could look into this. Everything should now be working in v1.8.1. Can you check that it works for you and close this issue if so. The new version is live on Firefox, it will be a little while still until it goes live on Chrome though.

it work now, But sometimes collapse to remove
![image](https://user-images.githubusercontent.com/22098092/83340529-8e8c2500-a303-11ea-8653-2ba3497d9797.png)

**Comment by mgziminsky** [comment]
Sorry, i'm not quite sure what you are asking. If you want it to remove sponsored posts instead of collapsing them, change this option:
<img src="https://user-images.githubusercontent.com/1260554/83341629-f5deb080-a2d4-11ea-9919-632ec174be71.png">

**Comment by Pezor** [comment]
@mgziminsky Works like a charm! Thank you

**Comment by Krashlog** [comment]
So... I guess I'll have to wait to win the "new FB version" lottery for this extension to work again? Still on legacy Facebook, and the extension doesn't work anymore, tried everything in this thread but still seeing sponsored posts...

**Comment by mgziminsky** [comment]
@Krashlog 

Since I am now on the new style, i can't really look into updates they make to the new one, I could try switching back to classic, but I'm afraid that then I wouldn't be able to get back to the new design. Fixing it should be simple though if you are willing and able to help me out some. Open a new issue and try following the instructions here: https://github.com/mgziminsky/FacebookTrackingRemoval/wiki/How-to-identify-selector-for-ads-not-being-blocked

The instructions are a little out of date, but the procedure is the same, FB just has fancier obfuscation now. The testing area under advanced options may not work for more advanced situations now, but if you attach screenshots like above, I should be able to figure out what is needed. I'll see about updating the testing options to work with the my new detection scheme in the next version as well to make it easier.

**Comment by Krashlog** [comment]
Thanks, don't switch back to classic... I'll have a look and share what I find. With my usual luck, I might be the last person on Earth to receive the new FB version! ;-)

**Comment by Pezor** [comment]
I noticed that suggested posts are not being properly removed, anyone having the same issue?
![obrazek](https://user-images.githubusercontent.com/6975523/84591720-f5035e00-ae40-11ea-95c9-368de78a2db8.png)

**Comment by mgziminsky** [comment]
It's likely those need an update too, but I haven't seen one in a very long time. Please open a new issue with any details you can provide. I'm going to lock this thread since closed issues aren't meant as discussion boards.
